elasticsearch:
  host: localhost:9200
  index: items
  type: items
search:
  aggregations:
    categories: 
      size: 10
      field: categories
      position: 90
      conjunction: true
      type: terms
      title: Categories
